export const countries: any = {
  AFG: { code: 'AFG', name: 'Afghanistan' },
  ALB: { code: 'ALB', name: 'Albania' },
  DZA: { code: 'DZA', name: 'Algeria' },
  AND: { code: 'AND', name: 'Andorra' },
  AGO: { code: 'AGO', name: 'Angola' },
  ARG: { code: 'ARG', name: 'Argentina' },
  ARM: { code: 'ARM', name: 'Armenia' },
  AUS: { code: 'AUS', name: 'Australia' },
  AUT: { code: 'AUT', name: 'Austria' },
  AZE: { code: 'AZE', name: 'Azerbaijan' },

  BHS: { code: 'BHS', name: 'Bahamas' },
  BHR: { code: 'BHR', name: 'Bahrain' },
  BGD: { code: 'BGD', name: 'Bangladesh' },
  BRB: { code: 'BRB', name: 'Barbados' },
  BLR: { code: 'BLR', name: 'Belarus' },
  BEL: { code: 'BEL', name: 'Belgium' },
  BLZ: { code: 'BLZ', name: 'Belize' },
  BEN: { code: 'BEN', name: 'Benin' },
  BTN: { code: 'BTN', name: 'Bhutan' },
  BOL: { code: 'BOL', name: 'Bolivia' },
  BIH: { code: 'BIH', name: 'Bosnia and Herzegovina' },
  BWA: { code: 'BWA', name: 'Botswana' },
  BRA: { code: 'BRA', name: 'Brazil' },
  BRN: { code: 'BRN', name: 'Brunei' },
  BGR: { code: 'BGR', name: 'Bulgaria' },
  BFA: { code: 'BFA', name: 'Burkina Faso' },
  BDI: { code: 'BDI', name: 'Burundi' },

  CAN: { code: 'CAN', name: 'Canada' },

  KHM: { code: 'KHM', name: 'Cambodia' },
  CMR: { code: 'CMR', name: 'Cameroon' },
  CAF: { code: 'CAF', name: 'Central African Republic' },
  TCD: { code: 'TCD', name: 'Chad' },
  CIV: { code: 'CIV', name: 'Ivory Coast' },
  CHL: { code: 'CHL', name: 'Chile' },
  CHN: { code: 'CHN', name: 'China' },
  COL: { code: 'COL', name: 'Colombia' },
  COM: { code: 'COM', name: 'Comoros' },
  COG: { code: 'COG', name: 'Congo' },
  COD: { code: 'COD', name: 'Democratic Republic of the Congo' },
  CRI: { code: 'CRI', name: 'Costa Rica' },

  HRV: { code: 'HRV', name: 'Croatia' },
  CUB: { code: 'CUB', name: 'Cuba' },
  CYP: { code: 'CYP', name: 'Cyprus' },
  CZE: { code: 'CZE', name: 'Czech Republic' },
  DNK: { code: 'DNK', name: 'Denmark' },
  DJI: { code: 'DJI', name: 'Djibouti' },
  DOM: { code: 'DOM', name: 'Dominican Republic' },
  ECU: { code: 'ECU', name: 'Ecuador' },
  EGY: { code: 'EGY', name: 'Egypt' },
  SLV: { code: 'SLV', name: 'El Salvador' },
  GNQ: { code: 'GNQ', name: 'Equatorial Guinea' },
  ERI: { code: 'ERI', name: 'Eritrea' },
  EST: { code: 'EST', name: 'Estonia' },
  ETH: { code: 'ETH', name: 'Ethiopia' },

  FIN: { code: 'FIN', name: 'Finland' },
  FRA: { code: 'FRA', name: 'France' },
  GAB: { code: 'GAB', name: 'Gabon' },
  GMB: { code: 'GMB', name: 'Gambia' },
  GEO: { code: 'GEO', name: 'Georgia' },
  DEU: { code: 'DEU', name: 'Germany' },
  GHA: { code: 'GHA', name: 'Ghana' },
  GRC: { code: 'GRC', name: 'Greece' },
  GTM: { code: 'GTM', name: 'Guatemala' },
  HND: { code: 'HND', name: 'Honduras' },
  HUN: { code: 'HUN', name: 'Hungary' },
  ISL: { code: 'ISL', name: 'Iceland' },
  IND: { code: 'IND', name: 'India' },
  IDN: { code: 'IDN', name: 'Indonesia' },
  IRN: { code: 'IRN', name: 'Iran' },
  IRQ: { code: 'IRQ', name: 'Iraq' },
  IRL: { code: 'IRL', name: 'Ireland' },
  ISR: { code: 'ISR', name: 'Israel' },
  ITA: { code: 'ITA', name: 'Italy' },

  JAM: { code: 'JAM', name: 'Jamaica' },
  JPN: { code: 'JPN', name: 'Japan' },
  KAZ: { code: 'KAZ', name: 'Kazakhstan' },
  KEN: { code: 'KEN', name: 'Kenya' },
  KWT: { code: 'KWT', name: 'Kuwait' },
  LVA: { code: 'LVA', name: 'Latvia' },
  LBN: { code: 'LBN', name: 'Lebanon' },
  LBY: { code: 'LBY', name: 'Libya' },
  LTU: { code: 'LTU', name: 'Lithuania' },
  LUX: { code: 'LUX', name: 'Luxembourg' },
  MDG: { code: 'MDG', name: 'Madagascar' },
  MWI: { code: 'MWI', name: 'Malawi' },
  MYS: { code: 'MYS', name: 'Malaysia' },
  MEX: { code: 'MEX', name: 'Mexico' },
  MNG: { code: 'MNG', name: 'Mongolia' },
  MAR: { code: 'MAR', name: 'Morocco' },

  NPL: { code: 'NPL', name: 'Nepal' },
  NLD: { code: 'NLD', name: 'Netherlands' },
  NZL: { code: 'NZL', name: 'New Zealand' },
  NGA: { code: 'NGA', name: 'Nigeria' },
  NOR: { code: 'NOR', name: 'Norway' },
  OMN: { code: 'OMN', name: 'Oman' },

  PAK: { code: 'PAK', name: 'Pakistan' },
  PAN: { code: 'PAN', name: 'Panama' },
  PER: { code: 'PER', name: 'Peru' },
  PHL: { code: 'PHL', name: 'Philippines' },
  POL: { code: 'POL', name: 'Poland' },
  PRT: { code: 'PRT', name: 'Portugal' },
  QAT: { code: 'QAT', name: 'Qatar' },
  ROU: { code: 'ROU', name: 'Romania' },
  RUS: { code: 'RUS', name: 'Russia' },

  SAU: { code: 'SAU', name: 'Saudi Arabia' },
  SEN: { code: 'SEN', name: 'Senegal' },
  SGP: { code: 'SGP', name: 'Singapore' },
  LKA: { code: 'LKA', name: 'Sri Lanka' },

  ZAF: { code: 'ZAF', name: 'South Africa' },
  ESP: { code: 'ESP', name: 'Spain' },
  SWE: { code: 'SWE', name: 'Sweden' },
  CHE: { code: 'CHE', name: 'Switzerland' },
  THA: { code: 'THA', name: 'Thailand' },
  TUN: { code: 'TUN', name: 'Tunisia' },
  TUR: { code: 'TUR', name: 'Turkey' },
  TZA: { code: 'TZA', name: 'Tanzania' },

  UKR: { code: 'UKR', name: 'Ukraine' },
  ARE: { code: 'ARE', name: 'United Arab Emirates' },
  GBR: { code: 'GBR', name: 'United Kingdom' },
  USA: { code: 'USA', name: 'United States' },
  UGA: { code: 'UGA', name: 'Uganda' },
  UZB: { code: 'UZB', name: 'Uzbekistan' },
  VNM: { code: 'VNM', name: 'Vietnam' },
  VEN: { code: 'VEN', name: 'Venezuela' },
  ZMB: { code: 'ZMB', name: 'Zambia' },
  ZWE: { code: 'ZWE', name: 'Zimbabwe' },
};


export const   providers = [
  'evolution',
  'playtech',
  'rubyplay',
  'nolimit',
  'habanero',
  'skywind',
  'kalamba',
  'ezugi',
  'quickspin',
  '3oaks',
  'voltent',
  'thunderkick',
  'kagaming',
  '1spin4win',
  'alg',
  'gameart',
  'mrslotty',
  'mascot',
  'groove',
  'lucky',
  '5men',
  'avatarux',
  'turbogames',
  'softswiss',
  'yggdrasil',
  'platipus',
  'truelab',
  'netgame',
  'amigo',
  'belatra',
  'onlyplay',
  'triplecherry',
  'popiplay',
  'gamebeat',
  'zillion',
  'jaderabbit',
  'clawbuster',
  'slotmill',
  'winfinity',
  'atmosphera',
  'technology',
  'gamezix',
  'fantasma',
  'pgsoft',
  'smartsoft',
];

export const allCategories = [
  {
    title: 'All Games',
    icon: 'fa-solid fa-cubes-stacked',
    link: '/categories/all-games',
  },
  {
    title: 'Slots',
    icon: 'fa-solid fa-slot-machine',
    link: '/categories/slots',
  },
  {
    title: 'Card',
    icon: 'fa-solid fa-cards',
    link: '/categories/card',
  },
  {
    title: 'Crash',
    icon: 'fa-solid fa-rocket',
    link: '/categories/crash',
  },
  {
    title: 'Roulette',
    icon: 'fa-solid fa-tire',
    link: '/categories/roulette',
  },
  {
    title: 'Lottery',
    icon: 'fa-solid fa-ticket',
    link: '/categories/lottery',
  },
  {
    title: 'Poker',
    icon: 'fa-solid fa-spade',
    link: '/categories/poker',
  },
  {
    title: 'Mines',
    icon: 'fa-solid fa-land-mine-on',
    link: '/categories/mines',
  },

  {
    title: 'Craps',
    icon: 'fa-solid fa-dice',
    link: '/categories/craps',
  },
  {
    title: 'Casual',
    icon: 'fa-solid fa-gamepad',
    link: '/categories/casual',
  },
  {
    title: 'Fishing',
    icon: 'fa-solid fa-fishing-rod',
    link: '/categories/fishing',
  },
  {
    title: 'Video Poker',
    icon: 'fa-solid fa-coin',
    link: '/categories/video-poker',
  },
  {
    title: 'Scratch',
    icon: 'fa-solid fa-scribble',
    link: '/categories/scratch',
  },
  {
    title: 'Virtual Sports',
    icon: 'fa-solid fa-sportsball',
    link: '/categories/virtual-sports',
  },
];
